// Generated by scripts/domain-packages.mjs. Do not edit.
import type { DomainRendererContribution, DomainRendererHost } from '@sciforge/domain-sdk/host'
import { defineInstalledRendererDomainEntrySet } from '@sciforge/domain-sdk/renderer'
import { createDomainRendererEntry as createDomainRendererEntry0 } from '@sciforge/domain-anchored-comments/renderer'
import { createDomainRendererEntry as createDomainRendererEntry1 } from '@sciforge/domain-artifact-versions/renderer'
import { createDomainRendererEntry as createDomainRendererEntry2 } from '@sciforge/domain-browser-preview/renderer'
import { createDomainRendererEntry as createDomainRendererEntry3 } from '@sciforge/domain-change-inspector/renderer'
import { createDomainRendererEntry as createDomainRendererEntry4 } from '@sciforge/domain-computer-use/renderer'
import { createDomainRendererEntry as createDomainRendererEntry5 } from '@sciforge/domain-create-loop/renderer'
import { createDomainRendererEntry as createDomainRendererEntry6 } from '@sciforge/domain-dataset-api/renderer'
import { createDomainRendererEntry as createDomainRendererEntry7 } from '@sciforge/domain-evidence-dag/renderer'
import { createDomainRendererEntry as createDomainRendererEntry8 } from '@sciforge/domain-git-checkpoints/renderer'
import { createDomainRendererEntry as createDomainRendererEntry9 } from '@sciforge/domain-life-science-preview/renderer'
import { createDomainRendererEntry as createDomainRendererEntry10 } from '@sciforge/domain-paper-radar/renderer'
import { createDomainRendererEntry as createDomainRendererEntry11 } from '@sciforge/domain-project-dag/renderer'
import { createDomainRendererEntry as createDomainRendererEntry12 } from '@sciforge/domain-remote-ssh/renderer'
import { createDomainRendererEntry as createDomainRendererEntry13 } from '@sciforge/domain-research-checkpoints/renderer'
import { createDomainRendererEntry as createDomainRendererEntry14 } from '@sciforge/domain-research-dossier/renderer'
import { createDomainRendererEntry as createDomainRendererEntry15 } from '@sciforge/domain-scientific-plotting/renderer'
import { createDomainRendererEntry as createDomainRendererEntry16 } from '@sciforge/domain-terminal/renderer'
import { createDomainRendererEntry as createDomainRendererEntry17 } from '@sciforge/domain-visual-review/renderer'
import { installedDomainPackages } from '@shared/installed-domain-packages'
import type { VisibleContextComponentSnapshot } from '@shared/visible-context'
import { rendererCapabilityClient } from '../lib/capability-client'
import { openSafeExternalUrl } from '../lib/open-external'
import {
  inspectRegisteredVisibleContextTargetAt,
  inspectRegisteredVisibleContextTextSelection,
  registerVisibleContextComponent,
  registerVisibleContextVisualTarget
} from '../lib/visible-context'
import { domainRendererNavigationHost } from './domain-renderer-navigation'

let rendererContributions: readonly DomainRendererContribution[] = []
const domainHost: DomainRendererHost = {
  capabilityInvoker: rendererCapabilityClient,
  contributions: {
    list: (kind) => rendererContributions.filter((contribution) => contribution.kind === kind)
  },
  openExternal: async (url) => {
    await openSafeExternalUrl(url)
  },
  workspace: {
    pickFile: (request) => window.sciforge.pickFile(request),
    openRemoteSession: async (input) => {
      await window.sciforge.remoteWorkspace.attach(input)
    }
  },
  ...domainRendererNavigationHost,
  visibleContext: {
    registerComponent: (component) => registerVisibleContextComponent(
      component as VisibleContextComponentSnapshot
    ),
    registerVisualTarget: ({ element, ...input }) => registerVisibleContextVisualTarget({
      ...input,
      ...(element ? { element: element as () => Element | null } : {})
    }),
    inspectRegisteredTargetAt: inspectRegisteredVisibleContextTargetAt,
    inspectRegisteredTextSelection: inspectRegisteredVisibleContextTextSelection
  }
}

export const installedRendererDomainEntrySet = defineInstalledRendererDomainEntrySet<unknown>(
  installedDomainPackages,
  [
    createDomainRendererEntry0(domainHost),
    createDomainRendererEntry1(domainHost),
    createDomainRendererEntry2(domainHost),
    createDomainRendererEntry3(domainHost),
    createDomainRendererEntry4(domainHost),
    createDomainRendererEntry5(domainHost),
    createDomainRendererEntry6(domainHost),
    createDomainRendererEntry7(domainHost),
    createDomainRendererEntry8(domainHost),
    createDomainRendererEntry9(domainHost),
    createDomainRendererEntry10(domainHost),
    createDomainRendererEntry11(domainHost),
    createDomainRendererEntry12(domainHost),
    createDomainRendererEntry13(domainHost),
    createDomainRendererEntry14(domainHost),
    createDomainRendererEntry15(domainHost),
    createDomainRendererEntry16(domainHost),
    createDomainRendererEntry17(domainHost)
  ]
)
rendererContributions = Object.freeze(installedRendererDomainEntrySet.contributions.map((contribution) => Object.freeze({
  id: contribution.declaration.id,
  kind: contribution.declaration.kind,
  packageName: contribution.packageName,
  owner: contribution.owner,
  ...(contribution.contract === undefined ? {} : { contract: contribution.contract }),
  value: contribution.value
})))
